// Combined All Quest Lines
const questLines = [
  require('./asp_fragments_quest.js'),
  require('./burlap_pants_quest.js'),
  require('./clown_court_quest.js'),
  require('./cyberneticEnhancement_quest.js'),
  require('./digitalGraffiti_quest.js'),
  require('./droneSwarmCommander_quest.js'),
  require('./holographicNightclub_quest.js'),
  require('./memoryMerchant_quest.js'),
  require('./mutantCookingShow_quest.js'),
  require('./mutantpetrescue_quest.js'),
  require('./neonStreetRacing_quest.js'),
  require('./std_collector_quest.js'),
  require('./syntheticEmotions_quest.js'),
  require('./syntheticPets_quest.js'),
  require('./trash_octopus_quest.js'),
  require('./undergroundfarming_quest.js'),
  require('./vending_machine_quest.js'),
  require('./virtualRealityAddiction_quest.js'),
  require('./wastelandamusementpark_quest.js'),
  require('./wastelandartgallery_quest.js'),
  require('./wastelandbotanicalgardens_quest.js'),
  require('./wastelandcircus_quest.js'),
  require('./wastelandculinarycompetition_quest.js'),
  require('./wastelandfashion_quest.js'),
  require('./wastelandfilmfestival_quest.js'),
  require('./wastelandhistorians_quest.js'),
  require('./wastelandhotspringsresort_quest.js'),
  require('./wastelandlibrarynetwork_quest.js'),
  require('./wastelandmuseumofhistory_quest.js'),
  require('./wastelandmusicfestival_quest.js'),
  require('./wastelandobservatory_quest.js'),
  require('./wastelandolympics_quest.js'),
  require('./wastelandpostalservice_quest.js'),
  require('./wastelandRadioDJ_quest.js'),
  require('./wastelandradionetwork_quest.js'),
  require('./wastelandsportsleague_quest.js'),
  require('./wastelandtheatertroupe_quest.js'),
  require('./wastelandtradingcaravan_quest.js'),
  require('./wastelanduniversity_quest.js')
];

module.exports = questLines;