// move_all_ai_scripts.js
// Script to move all AI-generated scripts to a single folder and rename it

const fs = require('fs');
const path = require('path');

console.log("=== MegaEarth 2049 AI Scripts Organizer ===");
console.log("This script will move all AI-generated scripts to a single folder and rename it.");
console.log("Starting organization process...\n");

// Current scripts directory
const currentDir = 'disease_system_scripts';
// New directory name
const newDir = 'AI_generated_scripts';

// Create new directory if it doesn't exist
if (!fs.existsSync(newDir)) {
    console.log(`Creating ${newDir} directory...`);
    fs.mkdirSync(newDir);
    
    // If the current directory exists, copy its contents to the new directory
    if (fs.existsSync(currentDir)) {
        const files = fs.readdirSync(currentDir);
        for (const file of files) {
            const sourcePath = path.join(currentDir, file);
            const destPath = path.join(newDir, file);
            
            console.log(`Moving ${sourcePath} to ${destPath}...`);
            
            try {
                // Read the content of the file
                const content = fs.readFileSync(sourcePath, 'utf8');
                
                // Write the content to the destination
                fs.writeFileSync(destPath, content);
                
                console.log(`Successfully moved ${file} to ${newDir} folder.`);
            } catch (error) {
                console.error(`Error moving ${file}:`, error.message);
            }
        }
        
        // Remove the old directory
        console.log(`Removing ${currentDir} directory...`);
        fs.rmdirSync(currentDir, { recursive: true });
    }
}

// List of additional AI-generated scripts to move
const aiScripts = [
    // Quest generation scripts
    'generate_quest_lines.js',
    'generate_more_quest_lines.js',
    'generate_more_quest_lines_batch2.js',
    'generate_more_quest_lines_batch3.js',
    'generate_more_quest_lines_batch4.js',
    'generate_more_quest_lines_batch5.js',
    'generate_single_quest_line.js',
    'combine_all_quest_lines.js',
    'add_all_quest_lines.js',
    'quest_line_helper.js',
    'new_quest_lines.js',
    'new_optional_quest_lines.js',
    'optional_quest_lines.js',
    'add_new_quest_lines.js',
    'add_optional_quest_lines.js',
    'more_optional_quest_lines.js',
    'more_optional_quest_npcs.js',
    'add_more_optional_quest_npcs.js',
    
    // NPC-related scripts
    'minor_npcs.js',
    'add_minor_npcs.js',
    'quest_hint_npcs.js',
    'add_quest_hint_npcs.js',
    'quest_helper_npcs.js',
    'add_quest_helper_npcs.js',
    
    // Individual quest scripts
    'trash_octopus_quest.js',
    'burlap_pants_quest.js',
    'clown_court_quest.js',
    'vending_machine_quest.js',
    'std_collector_quest.js',
    'asp_fragments_quest.js',
    'digitalGraffiti_quest.js',
    'syntheticPets_quest.js',
    'holographicNightclub_quest.js',
    'undergroundfarming_quest.js',
    'wastelandpostalservice_quest.js',
    'syntheticEmotions_quest.js',
    'wastelandartgallery_quest.js',
    'mutantcookingshow_quest.js',
    'neonStreetRacing_quest.js',
    'wastelandhistorians_quest.js',
    'memoryMerchant_quest.js',
    'droneSwarmCommander_quest.js',
    'mutantpetrescue_quest.js',
    'cyberneticEnhancement_quest.js',
    
    // Summary files
    'new_quest_lines_summary.md',
    'more_optional_quest_lines_summary.md',
    'minor_npcs_summary.md',
    'quest_hint_npcs_summary.md',
    'quest_helper_npcs_summary.md',
    'all_quest_lines_summary.md'
];

let movedCount = 0;

// Move each script to the AI_generated_scripts directory
for (const file of aiScripts) {
    const sourcePath = path.join('.', file);
    const destPath = path.join(newDir, file);
    
    if (fs.existsSync(sourcePath)) {
        console.log(`Moving ${sourcePath} to ${destPath}...`);
        
        try {
            // Read the content of the file
            const content = fs.readFileSync(sourcePath, 'utf8');
            
            // Write the content to the destination
            fs.writeFileSync(destPath, content);
            
            // Delete the original file
            fs.unlinkSync(sourcePath);
            
            console.log(`Successfully moved ${file} to ${newDir} folder.`);
            movedCount++;
        } catch (error) {
            console.error(`Error moving ${file}:`, error.message);
        }
    } else {
        console.log(`File ${sourcePath} does not exist or has already been moved.`);
    }
}

// Update the README.md file in the AI_generated_scripts directory
const readmeContent = `# AI Generated Scripts

This folder contains all the scripts generated by AI for MegaEarth 2049.

## Disease System Scripts

- **add_all_diseases.js**: Master script that runs all disease-related scripts in sequence
- **add_diseases.js**: Adds the first batch of diseases
- **disease_animations.js**: Sets up animations for the first batch of diseases
- **add_diseases_batch2.js**: Adds the second batch of diseases
- **disease_animations_batch2.js**: Sets up animations for the second batch of diseases
- **add_minor_ailments.js**: Adds minor ailments
- **minor_ailment_animations.js**: Sets up animations for minor ailments
- **minor_ailment_dialogue.js**: Sets up dialogue for minor ailments
- **add_mental_illnesses.js**: Adds mental illnesses
- **mental_illness_animations.js**: Sets up animations for mental illnesses
- **mental_illness_dialogue.js**: Sets up dialogue for mental illnesses

## Quest Generation Scripts

- **generate_quest_lines.js**: Generates quest lines
- **generate_more_quest_lines.js**: Generates additional quest lines
- **generate_more_quest_lines_batch2.js**: Generates batch 2 of additional quest lines
- **generate_more_quest_lines_batch3.js**: Generates batch 3 of additional quest lines
- **generate_more_quest_lines_batch4.js**: Generates batch 4 of additional quest lines
- **generate_more_quest_lines_batch5.js**: Generates batch 5 of additional quest lines
- **generate_single_quest_line.js**: Generates a single quest line
- **combine_all_quest_lines.js**: Combines all quest lines
- **add_all_quest_lines.js**: Adds all quest lines to the game
- **quest_line_helper.js**: Helper functions for quest lines
- **new_quest_lines.js**: New quest lines
- **new_optional_quest_lines.js**: New optional quest lines
- **optional_quest_lines.js**: Optional quest lines
- **add_new_quest_lines.js**: Adds new quest lines to the game
- **add_optional_quest_lines.js**: Adds optional quest lines to the game
- **more_optional_quest_lines.js**: More optional quest lines
- **more_optional_quest_npcs.js**: More optional quest NPCs
- **add_more_optional_quest_npcs.js**: Adds more optional quest NPCs to the game

## NPC-Related Scripts

- **minor_npcs.js**: Minor NPCs
- **add_minor_npcs.js**: Adds minor NPCs to the game
- **quest_hint_npcs.js**: Quest hint NPCs
- **add_quest_hint_npcs.js**: Adds quest hint NPCs to the game
- **quest_helper_npcs.js**: Quest helper NPCs
- **add_quest_helper_npcs.js**: Adds quest helper NPCs to the game

## Individual Quest Scripts

- **trash_octopus_quest.js**: Trash Octopus quest
- **burlap_pants_quest.js**: Burlap Pants quest
- **clown_court_quest.js**: Clown Court quest
- **vending_machine_quest.js**: Vending Machine quest
- **std_collector_quest.js**: STD Collector quest
- **asp_fragments_quest.js**: ASP Fragments quest
- **digitalGraffiti_quest.js**: Digital Graffiti quest
- **syntheticPets_quest.js**: Synthetic Pets quest
- **holographicNightclub_quest.js**: Holographic Nightclub quest
- **undergroundfarming_quest.js**: Underground Farming quest
- **wastelandpostalservice_quest.js**: Wasteland Postal Service quest
- **syntheticEmotions_quest.js**: Synthetic Emotions quest
- **wastelandartgallery_quest.js**: Wasteland Art Gallery quest
- **mutantcookingshow_quest.js**: Mutant Cooking Show quest
- **neonStreetRacing_quest.js**: Neon Street Racing quest
- **wastelandhistorians_quest.js**: Wasteland Historians quest
- **memoryMerchant_quest.js**: Memory Merchant quest
- **droneSwarmCommander_quest.js**: Drone Swarm Commander quest
- **mutantpetrescue_quest.js**: Mutant Pet Rescue quest
- **cyberneticEnhancement_quest.js**: Cybernetic Enhancement quest

## Utility Scripts

- **move_gamefaqs.js**: Moves all GameFAQs files to the GameFAQs folder
- **move_specific_faqs.js**: Moves specific FAQ files to the GameFAQs folder
- **move_disease_scripts.js**: Moves all disease-related scripts to a folder
- **move_all_ai_scripts.js**: Moves all AI-generated scripts to this folder

## Documentation

- **new_quest_lines_summary.md**: Summary of new quest lines
- **more_optional_quest_lines_summary.md**: Summary of more optional quest lines
- **minor_npcs_summary.md**: Summary of minor NPCs
- **quest_hint_npcs_summary.md**: Summary of quest hint NPCs
- **quest_helper_npcs_summary.md**: Summary of quest helper NPCs
- **all_quest_lines_summary.md**: Summary of all quest lines

The disease system is documented in \`GameFAQs/FAQ_11_Disease_System.md\`.
`;

const readmePath = path.join(newDir, 'README.md');
fs.writeFileSync(readmePath, readmeContent);
console.log(`Created README.md in ${newDir} folder.`);

// Move this script to the AI_generated_scripts directory
const thisScriptPath = path.join('.', 'move_all_ai_scripts.js');
const thisScriptDestPath = path.join(newDir, 'move_all_ai_scripts.js');

if (fs.existsSync(thisScriptPath)) {
    console.log(`Moving ${thisScriptPath} to ${thisScriptDestPath}...`);
    
    try {
        // Read the content of the file
        const content = fs.readFileSync(thisScriptPath, 'utf8');
        
        // Write the content to the destination
        fs.writeFileSync(thisScriptDestPath, content);
        
        console.log(`Successfully moved ${thisScriptPath} to ${newDir} folder.`);
        movedCount++;
    } catch (error) {
        console.error(`Error moving ${thisScriptPath}:`, error.message);
    }
}

console.log(`\nMoved ${movedCount} AI-generated scripts to the ${newDir} folder.`);
console.log("\n=== Organization Complete ===");
console.log(`All AI-generated scripts have been moved to the ${newDir} folder.`);
