// move_powershell_scripts.js
// Script to move PowerShell scripts to the AI_POWERSHELL_SCRIPTS folder

const fs = require('fs');
const path = require('path');

console.log("=== MegaEarth 2049 PowerShell Scripts Organizer ===");
console.log("This script will move PowerShell scripts to the AI_POWERSHELL_SCRIPTS folder.");
console.log("Starting organization process...\n");

// Create the AI_POWERSHELL_SCRIPTS directory if it doesn't exist
if (!fs.existsSync('AI_POWERSHELL_SCRIPTS')) {
    console.log(`Creating AI_POWERSHELL_SCRIPTS directory...`);
    fs.mkdirSync('AI_POWERSHELL_SCRIPTS');
}

// List of PowerShell scripts to move
const powershellScripts = [
    'copy_art_assets.ps1',
    'copy_missing_assets.ps1',
    'create_art_assets.ps1',
    'create_boss_art_assets.ps1',
    'create_missing_art_assets.ps1',
    'generate_boss_placeholder_sprites.ps1',
    'generate_placeholder_sprites.ps1',
    'update_boss_enemies_json.ps1',
    'update_enemies_json.ps1'
];

let movedCount = 0;

// Move each script to the AI_POWERSHELL_SCRIPTS directory
for (const file of powershellScripts) {
    const sourcePath = path.join('.', file);
    const destPath = path.join('AI_POWERSHELL_SCRIPTS', file);
    
    if (fs.existsSync(sourcePath)) {
        console.log(`Moving ${sourcePath} to ${destPath}...`);
        
        try {
            // Read the content of the file
            const content = fs.readFileSync(sourcePath, 'utf8');
            
            // Write the content to the destination
            fs.writeFileSync(destPath, content);
            
            // Delete the original file
            fs.unlinkSync(sourcePath);
            
            console.log(`Successfully moved ${file} to AI_POWERSHELL_SCRIPTS folder.`);
            movedCount++;
        } catch (error) {
            console.error(`Error moving ${file}:`, error.message);
        }
    } else {
        console.log(`File ${sourcePath} does not exist or has already been moved.`);
    }
}

// Create a README.md file in the AI_POWERSHELL_SCRIPTS directory
const readmeContent = `# AI-Generated PowerShell Scripts

This folder contains PowerShell scripts generated by AI for MegaEarth 2049.

## Art Asset Scripts

- **copy_art_assets.ps1**: Copies art assets from source to destination
- **copy_missing_assets.ps1**: Copies missing art assets
- **create_art_assets.ps1**: Creates art assets
- **create_missing_art_assets.ps1**: Creates missing art assets
- **generate_placeholder_sprites.ps1**: Generates placeholder sprites

## Boss Scripts

- **create_boss_art_assets.ps1**: Creates boss art assets
- **generate_boss_placeholder_sprites.ps1**: Generates boss placeholder sprites
- **update_boss_enemies_json.ps1**: Updates boss enemies JSON

## Enemy Scripts

- **update_enemies_json.ps1**: Updates enemies JSON
`;

const readmePath = path.join('AI_POWERSHELL_SCRIPTS', 'README.md');
fs.writeFileSync(readmePath, readmeContent);
console.log(`Created README.md in AI_POWERSHELL_SCRIPTS folder.`);

// Move this script to the AI_generated_scripts directory
const thisScriptPath = path.join('.', 'move_powershell_scripts.js');
const thisScriptDestPath = path.join('AI_generated_scripts', 'move_powershell_scripts.js');

if (fs.existsSync(thisScriptPath)) {
    console.log(`Moving ${thisScriptPath} to ${thisScriptDestPath}...`);
    
    try {
        // Read the content of the file
        const content = fs.readFileSync(thisScriptPath, 'utf8');
        
        // Write the content to the destination
        fs.writeFileSync(thisScriptDestPath, content);
        
        console.log(`Successfully moved ${thisScriptPath} to AI_generated_scripts folder.`);
        movedCount++;
    } catch (error) {
        console.error(`Error moving ${thisScriptPath}:`, error.message);
    }
}

console.log(`\nMoved ${movedCount} PowerShell scripts to the AI_POWERSHELL_SCRIPTS folder.`);
console.log("\n=== Organization Complete ===");
console.log(`All PowerShell scripts have been moved to the AI_POWERSHELL_SCRIPTS folder.`);
